//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Afiliado
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Afiliado()
    {
        this.AfiliadoServicios = new HashSet<AfiliadoServicio>();
    }

    public int IdAfiliado { get; set; }
    public string RFC { get; set; }
    public string Nombre { get; set; }
    public string Telefono { get; set; }
    public string Direccion { get; set; }
    public string Coordenadas { get; set; }
    public Nullable<bool> Activo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AfiliadoServicio> AfiliadoServicios { get; set; }
}

public partial class AfiliadoServicio
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AfiliadoServicio()
    {
        this.Agenda = new HashSet<Agendum>();
        this.HorarioServicios = new HashSet<HorarioServicio>();
    }

    public int IdAfiliadoServicio { get; set; }
    public int IdServicio { get; set; }
    public string IdAfiliado { get; set; }
    public Nullable<bool> Activo { get; set; }

    public virtual Afiliado Afiliado { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Agendum> Agenda { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HorarioServicio> HorarioServicios { get; set; }
    public virtual Servicio Servicio { get; set; }
}

public partial class Agendum
{
    public int IdAgenda { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public Nullable<System.TimeSpan> Hora { get; set; }
    public int IdAfiliadoServicio { get; set; }
    public Nullable<bool> Activo { get; set; }

    public virtual AfiliadoServicio AfiliadoServicio { get; set; }
}

public partial class Cita
{
    public int IdCita { get; set; }
    public string IdPaciente { get; set; }
    public string Requisitos { get; set; }
    public int IdHorarioServicio { get; set; }
    public Nullable<int> Estatus { get; set; }

    public virtual HorarioServicio HorarioServicio { get; set; }
}

public partial class Horario
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Horario()
    {
        this.HorarioServicios = new HashSet<HorarioServicio>();
    }

    public int IdHorario { get; set; }
    public Nullable<System.TimeSpan> Inicio { get; set; }
    public Nullable<System.TimeSpan> Final { get; set; }
    public Nullable<bool> Lunes { get; set; }
    public Nullable<bool> Martes { get; set; }
    public Nullable<bool> Miercoles { get; set; }
    public Nullable<bool> Jueves { get; set; }
    public Nullable<bool> Sabado { get; set; }
    public Nullable<bool> Domingo { get; set; }
    public Nullable<bool> Activo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HorarioServicio> HorarioServicios { get; set; }
}

public partial class HorarioServicio
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public HorarioServicio()
    {
        this.Citas = new HashSet<Cita>();
    }

    public int IdHorarioServicio { get; set; }
    public int IdHorario { get; set; }
    public int IdAfiliadoServicio { get; set; }
    public Nullable<bool> Activo { get; set; }

    public virtual AfiliadoServicio AfiliadoServicio { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cita> Citas { get; set; }
    public virtual Horario Horario { get; set; }
}

public partial class Paciente
{
    public int IdPaciente { get; set; }
    public string CURP { get; set; }
    public string Nombre { get; set; }
    public string ApePaterno { get; set; }
    public string ApeMaterno { get; set; }
    public string Genero { get; set; }
    public Nullable<int> Edad { get; set; }
    public Nullable<System.DateTime> FechaNac { get; set; }
    public Nullable<bool> Activo { get; set; }
}

public partial class Resultado
{
    public int IdResultados { get; set; }
    public string IdPaciente { get; set; }
    public int IdServicio { get; set; }
    public string IdAfiliado { get; set; }
    public int IdCita { get; set; }
    public byte[] Resultado1 { get; set; }
}

public partial class Servicio
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Servicio()
    {
        this.AfiliadoServicios = new HashSet<AfiliadoServicio>();
    }

    public int IdServicio { get; set; }
    public string Nombre { get; set; }
    public string Descripcion { get; set; }
    public string Requisitos { get; set; }
    public Nullable<int> Duracion { get; set; }
    public Nullable<bool> Activo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AfiliadoServicio> AfiliadoServicios { get; set; }
}

public partial class Usuario
{
    public string IdUsuario { get; set; }
    public Nullable<int> Tipo { get; set; }
    public string Pass { get; set; }
}
