//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class JUMEntities : DbContext
{
    public JUMEntities()
        : base("name=JUMEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Afiliado> Afiliadoes { get; set; }
    public virtual DbSet<AfiliadoServicio> AfiliadoServicios { get; set; }
    public virtual DbSet<Agendum> Agenda { get; set; }
    public virtual DbSet<Cita> Citas { get; set; }
    public virtual DbSet<Horario> Horarios { get; set; }
    public virtual DbSet<HorarioServicio> HorarioServicios { get; set; }
    public virtual DbSet<Paciente> Pacientes { get; set; }
    public virtual DbSet<Resultado> Resultados { get; set; }
    public virtual DbSet<Servicio> Servicios { get; set; }
    public virtual DbSet<Usuario> Usuarios { get; set; }
}
